### ISSUE TITLE
How to install in Intellij

### ISSUE THREAD

**Issue by ginccc** [con-ceptive/quarkus-intellij-plugin#1]
Hi there!

Seems to be a great plugin. Intellij has not approved it yet. Is there a way to use it already?

Thanks
Gregor

**Comment by wglanzer** [comment]
Hi Gregor,
thank you for your question. JetBrains approved it like 30 minutes ago (https://plugins.jetbrains.com/plugin/14242-quarkus-integration)  - but I will add additional description anyway, this is a really good idea! 
It can be useful if you want to install a daily build or something like this.

**Comment by wglanzer** [comment]
Added documentation in README.md

**Comment by ginccc** [comment]
Nice! Looking forward to using it :-D
