### ISSUE TITLE
Multi project support

### ISSUE THREAD

**Issue by deejonz** [con-ceptive/quarkus-intellij-plugin#10]
I'm using a multi project structure using maven. There is one main project and a few other projects as libraries. The main project is including the libraries as dependencies using the SNAPSHOT version in the pom.xml. 
If I modify the libraries the changes are not picked up from the sources but instead from the local repository so for every single change to the libraries I need to recompile the code. How to handle that? This was working with no problem with the same setup using Spring boot.
I'm using the community version of intellij idea.

**Comment by wglanzer** [comment]
Hi @deejonz,
I don't know exactly what you are talking about, but it seems that this is more a quarkus related question, than a plugin one.
May I advise you to create an issue in https://github.com/quarkusio/quarkus?
If the "quarkus:dev" goal does not support this, I'm not able to include this feature out of the box - sorry..

**Comment by deejonz** [comment]
sorry for the confusion, I found how to implement that modifying the pom structure. Thanks.
