### ISSUE TITLE
 "--enable-preview" is ignored with the version 1.3.2

### ISSUE THREAD

**Issue by loranmercier** [con-ceptive/quarkus-intellij-plugin#11]
I use Java 22 and "--enable-preview" is ignored  with [io.quarkus.deployment.QuarkusAugmentor]

**Comment by wglanzer** [comment]
Hi @loranmercier,
is this really a bug / missing feature of the intellij plugin?
I think this belongs to the underlying quarkus framework itself

**Comment by wglanzer** [comment]
I'll close this issue, because it rather belongs to the quarkus framework instead of this plugin.
