### ISSUE TITLE
Gradle Support 

### ISSUE THREAD

**Issue by jnsfrg** [con-ceptive/quarkus-intellij-plugin#2]
Hi there, 
this seems exactly what I was looking for. A great Plugin! Is there already a way to make it work with Gradle projects or any plans to support Gradle ?

**Comment by wglanzer** [comment]
Hi Jonas, I am currently not really familiar with gradle - just the real basics of it. But anyway, supporting gradle is not a bad idea, because of its popularity. I am looking forward to implement this within the next few days/weeks, depending on how this is generally possible 👍

**Comment by wglanzer** [comment]
The gradle support is included in the next version (1.1.0) and should be available in the official jetbrains repository within the next few days. If you want to test it earlier, you could install it by downloading the file manually, see README if you need help installing it :) 

If you have any issues, please let me know - I just tested with the small official demo project of quarkus ( https://quarkus.io/guides/gradle-tooling ).
