### ISSUE TITLE
Impossible to distringuish the official plugin from RedHat and debugger integration

### ISSUE THREAD

**Issue by jreznot** [con-ceptive/quarkus-intellij-plugin#4]
Hi,
I would say that current plugin name is slightly misleading:

![image](https://user-images.githubusercontent.com/1066152/89649898-2d1ba000-d8ca-11ea-981f-6b8fd35a9565.png)

May be change it to something related to debugger or run configuration? Let's say `Quarkus Run Configuration` or `Quarkus Debug`?

Also, two plugins with the same icon look suspicious. I'd recommend to change icon or add some detail that is associated with debug/run.

**Comment by wglanzer** [comment]
I changed the plugin title and icon. Version update was requested, and the update should be available soon.

**Comment by jreznot** [comment]
Thank you so much!
