### ISSUE TITLE
Enhancement Reques: Support for Custom Quarkus Profiles in Run/Debug Configurations

### ISSUE THREAD

**Issue by heltonricardo** [con-ceptive/quarkus-intellij-plugin#8]
### Issue Description:
The current version of the IntelliJ plugin for Quarkus development automatically executes the "quarkus:dev" profile in Run/Debug configurations. While this is suitable for many scenarios, it limits users from utilizing other Quarkus profiles they might have defined for specific use cases, such as "quarkus:test" or custom profiles. To enhance the plugin's functionality and provide developers with more flexibility, I suggest adding support for using custom Quarkus profiles in Run/Debug configurations.

### Suggested Feature:
Support the use of custom Quarkus profiles in the Run/Debug Configurations window within the IntelliJ plugin for Quarkus. Allow users to specify the desired Quarkus profile for running their Quarkus applications in different modes, such as "quarkus:test," and any custom profiles they have defined in their Quarkus project configuration.

### Benefits:
- Increased Flexibility: Developers can choose from a range of Quarkus profiles to match specific development, testing, or production requirements.
- Custom Profile Support: Users can leverage any custom profiles they have defined, providing more control and adaptability in their Quarkus projects.
- Streamlined Development: By supporting custom profiles, developers can seamlessly switch between different configurations directly within the Run/Debug Configuration, reducing manual adjustments and saving time.

This enhancement will empower developers to work more efficiently with Quarkus by enabling the use of custom profiles tailored to their projects' distinct needs. Thank you for considering this suggestion, and I'm looking forward to seeing this feature in future updates of the plugin.

**Comment by wglanzer** [comment]
Hi @heltonricardo, I have rarely received such a well formulated feature request, thank you!
I will have a look at it as soon as possible and give you a first suggestion how something like this will look like.

**Comment by heltonricardo** [comment]
Thank you, @wglanzer, for considering the enhancement and for your kind response. Looking forward to any updates and improvements in the future. Many thanks!

**Comment by wglanzer** [comment]
Hi @heltonricardo, sorry for keep you waiting so long.
What do you think about this idea:
![runconfig_maven](https://github.com/wglanzer/quarkus-intellij-plugin/assets/14055002/b99fc374-2117-4867-a0d3-01aac4f1fcc9)

I included a "Goals" and "Profiles" Box, so you are free to define any custom goals and/or profiles.
Same for gradle and its "Tasks".
I removed the "compileBeforeLaunch" checkbox too and replaced it by adding "clean compile"/"clean assemble" by default into the "goals"/"tasks" section. This should make it more clear what the runconfig does in background.

Is this concept what you thought of, or am I completely wrong?

**Comment by heltonricardo** [comment]
Hey, @wglanzer 

I want to express my gratitude for the update to the plugin. The addition of support for different profiles aligns perfectly with my original suggestion. Thanks for making the plugin more versatile and user-friendly. I can't wait to test the latest version and experience the improvements firsthand!

Best regards!

**Comment by wglanzer** [comment]
I published a new version (1.3.0) of the plugin just now. It should be approved within the next two business days by the JetBrains team, so you are able to perform an upgrade out of the box on the regular JetBrains-IDE-Way.
