### ISSUE TITLE
Configuration property "Tasks" resets after IntelliJ restart

### ISSUE THREAD

**Issue by schmulschubiak** [con-ceptive/quarkus-intellij-plugin#9]
After changing the property "Tasks" in the configuration dialog, the value will not survive IntelliJ restart.

Plugin version: 1.3.0
IntelliJ version: IntelliJ IDEA 2023.2 (Ultimate Edition)

**Comment by wglanzer** [comment]
IntelliJ does strange things during option reading/writing... Should be fixed with plugin version 1.3.1 now, sorry for the inconvenience!

**Comment by schmulschubiak** [comment]
Thank you for your quick fix! And thanks for your clean and simple plugin, redhats own quarkus plugin is a mess!
